spring:
  jpa:
    database: mysql
    database-platform: org.hibernate.dialect.MySQL5InnoDBDialect
    generate-ddl: true
    hibernate:
      ddl-auto: update
      use-new-id-generator-mappings: true
    show-sql: true
    

  datasource:
    url: jdbc:mysql://localhost:3306/jensen
    username: root
    password: 1234

  resources:
    static-locations: classpath:/upload/, classpath:/static/
    
  servlet:
    multipart:
      max-file-size: 50MB
      max-request-size: 50MB
  mail:
    host: smtp.gmail.com
    port: 587
    username: 
    password: 
    properties: 
      mail:
        smtp:
          auth: true
          starttls:
            enable: true